### ISSUE TITLE
Permissions for translatewiki to push localisation changes

### ISSUE THREAD

**Issue by Abijeet** [Ajapaik/ajapaik_flutter_app#2]
We've added the Ajapaik Flutter app for [localisation on translatewiki.net](https://translatewiki.net/wiki/Special:Translate?action=translate&group=ajapaik-flutter-app), but the [translatewiki bot](https://github.com/translatewiki) does not have permissions to push the translations back to the GitHub repository. Please provide the bot with commit access.

```
  Error Output:                                                                
  ================                                                             
  ERROR: Permission to Ajapaik/ajapaik_flutter_app.git denied to translatewik  
  i.                                                                           
  fatal: Could not read from remote repository.                                
                                                                               
  Please make sure you have the correct access rights                          
  and the repository exists.             
```

**Comment by zache-fi** [comment]
Hi, added now translatewiki to the project. There should be now a pending invite
